# Site Settings
title: Busta's Dev Blog
url: https://busta.dev

# Build Settings
permalink: "/blog/:year/:month/:day/:title/"
sass:
  sass_dir: "_sass"
  style: compressed

# Collection Settings
collections:
  projects:
    output: false
  sections:
    output: false
  posts:
    output: true
  certifications:
    output: false

defaults:
- scope:
    path: ""
    type: "projects"
  values:
    permalink: "/:collection/:name/"
- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
- scope:
    path: ""
    type: "certifications"
  values:
    layout: "post"
    

# Plugin Settings
plugins:
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"
highlighter: rouge