# Site Settings
title: Busta's Dev Blog
url: https://busta.dev

# Build Settings
permalink: "/blog/:year/:month/:day/:title/"
sass:
  style: compressed

# Collection Settings
collections:
  games:
    output: true
  lectures:
    output: true
  sections:
    output: false
defaults:
- scope:
    path: ''
    type: games
  values:
    permalink: "/:collection/:name/"
defaults:
- scope:
    path: ''
    type: lectures
  values:
    permalink: "/:collection/:year/:month/:day/:name/"

# Plugin Settings
plugins:
  - jekyll-paginate
  - jemoji

paginate: 5
highlighter: rouge