# Site Settings
title: 'busta.dev'
description: >-
  Games, software and other projects developed by Ricardo Bustamante, a.k.a. Busta.
url: https://busta.dev

# Build Settings
permalink: "/blog/:year/:month/:day/:title/"
sass:
  sass_dir: "_sass"
  style: compressed

# Collection Settings
collections:
  projects:
    output: false
  posts:
    output: true
  certifications:
    output: false
  recipes:
    output: true

defaults:
- scope:
    path: ""
    type: "projects"
  values:
    permalink: "/:collection/:name/"
- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
- scope:
    path: ""
    type: "certifications"
  values:
    layout: "post"
- scope:
    path: ""
    type: "recipes"
  values:
    permalink: "/:path/"
    layout: "recipe"
    

# Plugin Settings
plugins:
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"
highlighter: rouge