# Site Settings
title: Busta's Dev Blog
url: https://busta.dev

# Build Settings
permalink: "/blog/:year/:month/:day/:title/"
sass:
  sass_dir: "_sass"
  style: compressed

# Collection Settings
collections:
  projects:
    output: false
  sections:
    output: false
  posts:
    output: true
  legal-pp:
    output: true
  legal-tac:
    output: true

defaults:
- scope:
    path: ""
    type: "projects"
  values:
    permalink: "/:collection/:name/"
- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
- scope:
    path: ""
    type: "legal-pp"
  values:
    permalink: "/legal/privacy-policy/:title/"
    contact: contact@busta.dev
    company_name: Busta Games
    layout: privacy-policy
- scope:
    path: ""
    type: "legal-tac"
  values:
    permalink: "/legal/terms-and-conditions/:title/"
    contact: contact@busta.dev
    company_name: Busta Games
    layout: terms-and-conditions

# Plugin Settings
plugins:
  - jekyll-paginate
  - jemoji

paginate: 6
paginate_path: "/blog/page:num/"
highlighter: rouge